# src/skill_extraction/skills.py

SKILLS = [
    "python",
    "java",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "next.js",
    "nextjs",
    "vue",
    "angular",
    "node.js",
    "nodejs",
    "express",
    "nestjs",
    "php",
    "laravel",
    "codeigniter",
    "mysql",
    "postgresql",
    "mongodb",
    "sql",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "git",
    "github",
    "excel",
    "power bi",
    "tableau",
    "figma",
    "photoshop",
    "illustrator",
    "seo",
    "sem",
    "google ads",
    "meta ads",
    "tensorflow",
    "pytorch",
    "machine learning",
    "data analysis",
    "powerpoint",
    "word",
    "linux",
    "rest api"
]
