SKILLS = [
    # === Programming Languages ===
    "python",
    "java",
    "javascript",
    "typescript",
    "html",
    "css",
    "php",
    "golang",
    "c#",
    "c++",
    "swift",
    "kotlin",
    "r",
    "scala",
    "matlab",
    "bash",
    "shell scripting",

    # === Frontend ===
    "react",
    "next.js",
    "vue",
    "angular",
    "tailwind",
    "bootstrap",
    "jquery",

    # === Backend & Framework ===
    "node.js",
    "express",
    "nestjs",
    "laravel",
    "codeigniter",
    "django",
    "flask",
    "fastapi",
    "spring boot",

    # === Database ===
    "mysql",
    "postgresql",
    "mongodb",
    "sql",
    "redis",
    "graphql",
    "sqlite",
    "oracle",
    "bigquery",
    "snowflake",
    "redshift",
    "elasticsearch",

    # === Cloud & DevOps ===
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "firebase",
    "git",
    "github",
    "linux",
    "ci/cd",
    "terraform",
    "ansible",
    "jenkins",

    # === Data Science & Analytics ===
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "keras",
    "machine learning",
    "deep learning",
    "data analysis",
    "data visualization",
    "statistics",
    "statistical modeling",
    "predictive modeling",
    "time-series analysis",
    "regression",
    "hypothesis testing",
    "a/b testing",
    "nlp",
    "computer vision",
    "spark",
    "hadoop",
    "kafka",
    "etl",
    "data warehousing",
    "data engineering",
    "looker",
    "google data studio",
    "sas",

    # === BI & Office Tools ===
    "excel",
    "power bi",
    "tableau",
    "powerpoint",
    "word",

    # === Design ===
    "figma",
    "photoshop",
    "illustrator",
    "adobe xd",
    "canva",
    "sketch",

    # === Marketing ===
    "seo",
    "sem",
    "google ads",
    "meta ads",
    "google analytics",
    "email marketing",
    "content marketing",
    "social media marketing",
    "copywriting",

    # === Mobile ===
    "flutter",
    "react native",
    "android",
    "ios",

    # === API & Integration ===
    "rest api",
    "graphql",
    "microservices",
    "websocket",

    # === Soft Skills ===
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "collaboration",
    "negotiation",
    "project management",
    "agile",
    "scrum",
    "analytical skills",

    # === Network & Security ===
    "bgp",
    "cisco",
    "cisco asa",
    "cisco nexus",
    "cisco routers",
    "compliance auditing",
    "cryptography",
    "dns",
    "dhcp",
    "eigrp",
    "f5 load balancer",
    "firewalls",
    "firewall management",
    "firewall basics",
    "ids/ips",
    "incident management",
    "lan/wan",
    "malware analysis",
    "mpls",
    "nagios",
    "network monitoring",
    "network troubleshooting",
    "ospf",
    "qos",
    "routing basics",
    "siem tools",
    "sip",
    "soc operations",
    "solarwinds",
    "tcp/ip",
    "threat hunting",
    "voip",
    "vpn",
    "vpn setup",
]